apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userjava
  template:
    metadata:
      labels:
        app: userjava
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: trips
        image: registrylpg2295.azurecr.io/tripinsights/user-java:1.0
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kvname
            nodePublishSecretRef:                       # Only required when using service principal mode
              name: secrets-store-creds                 # Only required when using service principal mode
---
apiVersion: v1
kind: Service
metadata:
  name: userjava-service
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: userjava
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
