apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userjava
  template:
    metadata:
      labels:
        app: userjava
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: trips
        image: registrylpg2295.azurecr.io/tripinsights/user-java:1.0
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userjava-service
spec:
  type: ClusterIP
  selector:
    app: userjava
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
