apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripsinsights-poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripsinsights-poi
  template:
    metadata:
      labels:
        app: tripsinsights-poi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: tripsinsights-poi
        image: registrylpg2295.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
