apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
  labels:
    deploy: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - image: registrylpg2295.azurecr.io/tripinsights/poi:1.0
        imagePullPolicy: Always
        name: poi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: WEB_SERVER_BASE_URI
          value: 'http://0.0.0.0'
        - name: ASPNETCORE_ENVIRONMENT
          value: 'Production'
        - name: SQL_USER
          value: 'sqladmin'
        - name: SQL_SERVER
          value: 'sqlserverlpg2295.database.windows.net'
        envFrom:
        - secretRef:
            name: sql
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: poi
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80