apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: api
spec:
  provider: azure
  parameters:
    keyvaultName: acc-aks-keyvault
    objects:  |
      array:
        - |
          objectName: sql
          objectAlias: SQL_PASSWORD
          objectType: secret
          objectVersion: ""
    tenantId: fda2ba18-03e7-40e0-afe6-4e1eeae8465d