kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-full-access
  namespace: web
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-binding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-full-access
subjects:
- kind: Group
  namespace: web
  name: 7a32f88e-8987-42db-b428-c5dd6c3cd004 # web-dev group objectID