apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - image: registrylpg2295.azurecr.io/tripinsights/trips:1.0
        imagePullPolicy: Always
        name: trips
        ports: 
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: SQL_USER
          value: 'sqladmin'
        - name: SQL_SERVER
          value: 'sqlserverlpg2295.database.windows.net'
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kvname
            nodePublishSecretRef:                       # Only required when using service principal mode
              name: secrets-store-creds                 # Only required when using service principal mode
---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: trips
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80